# Generated by Django 5.0.1 on 2026-01-31 13:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(help_text='Friendly name for this address', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('street1', models.CharField(max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='US', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default address for new shipments')),
            ],
            options={
                'db_table': 'saved_addresses',
                'ordering': ['-is_default', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(help_text='Friendly name for this package preset', max_length=100, unique=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('package_type', models.CharField(choices=[('box', 'Box'), ('envelope', 'Envelope'), ('pak', 'Pak'), ('tube', 'Tube')], default='box', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default package for new shipments')),
            ],
            options={
                'db_table': 'saved_packages',
                'ordering': ['-is_default', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_row_number', models.IntegerField(blank=True, db_index=True, help_text='Original row number in CSV file', null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='valid', help_text='Validation status of shipment', max_length=20)),
                ('validation_messages', models.JSONField(blank=True, default=list, help_text='Array of validation warnings/errors')),
                ('address_validation_provider', models.CharField(blank=True, choices=[('usps', 'USPS'), ('google', 'Google Maps'), ('smarty', 'Smarty Streets'), ('lob', 'Lob')], help_text='Which provider validated the addresses', max_length=20, null=True)),
                ('customs_description', models.TextField(blank=True, help_text='Customs declaration description (international shipments)', null=True)),
                ('customs_value', models.DecimalField(blank=True, decimal_places=2, help_text='Customs declaration value (international shipments)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, help_text='User-defined reference/order number', max_length=100, null=True)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['csv_row_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in ounces', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight_unit', models.CharField(choices=[('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')], default='oz', help_text='Unit of weight measurement', max_length=5)),
                ('package_type', models.CharField(choices=[('box', 'Box'), ('envelope', 'Envelope'), ('pak', 'Pak'), ('tube', 'Tube')], default='box', help_text='Type of package', max_length=20)),
                ('shipment', models.OneToOneField(help_text='Parent shipment', on_delete=django.db.models.deletion.CASCADE, related_name='package', to='shipping.shipment')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['shipment'],
            },
        ),
        migrations.CreateModel(
            name='ShippingServiceSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('priority_mail', 'Priority Mail'), ('ground_shipping', 'Ground Shipping')], help_text='Type of shipping service', max_length=30)),
                ('service_tier', models.CharField(choices=[('tier_1', 'Tier 1 (0-4 oz)'), ('tier_2', 'Tier 2 (4-8 oz)'), ('tier_3', 'Tier 3 (8-12 oz)'), ('tier_4', 'Tier 4 (12-16 oz)'), ('tier_5', 'Tier 5 (16+ oz)')], help_text='Service tier based on weight', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Shipping price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3)),
                ('auto_selected', models.BooleanField(default=True, help_text='True if auto-assigned by weight, False if manually selected')),
                ('shipment', models.OneToOneField(help_text='Parent shipment', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_service', to='shipping.shipment')),
            ],
            options={
                'db_table': 'shipping_service_selections',
                'ordering': ['shipment'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('purchased', 'Purchased')], db_index=True, default='draft', help_text='Current status of the upload session', max_length=20)),
                ('total_shipments', models.IntegerField(default=0, help_text='Total number of shipments in this session')),
                ('valid_shipments', models.IntegerField(default=0, help_text='Number of shipments with valid status')),
                ('warning_shipments', models.IntegerField(default=0, help_text='Number of shipments with warning status')),
                ('error_shipments', models.IntegerField(default=0, help_text='Number of shipments with error status')),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='True after purchase - prevents further edits')),
                ('purchase_date', models.DateTimeField(blank=True, help_text='Timestamp when session was purchased', null=True)),
                ('label_size', models.CharField(blank=True, choices=[('letter', 'Letter / A4'), ('4x6', '4x6 Label')], help_text='Label size selected at purchase', max_length=10, null=True)),
                ('terms_accepted', models.BooleanField(default=False, help_text='User acceptance of terms and conditions')),
            ],
            options={
                'db_table': 'upload_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_locked'], name='upload_sess_status_824bc7_idx'), models.Index(fields=['-created_at'], name='upload_sess_created_aa2eb7_idx')],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='upload_session',
            field=models.ForeignKey(help_text='Parent upload session', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipping.uploadsession'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('ship_from', 'Ship From'), ('ship_to', 'Ship To')], db_index=True, help_text='Ship From or Ship To', max_length=20)),
                ('name', models.CharField(help_text='Recipient/Sender name', max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('street1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('street2', models.CharField(blank=True, help_text='Street address line 2', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='2-letter state code', max_length=2)),
                ('zip_code', models.CharField(help_text='ZIP or ZIP+4', max_length=10)),
                ('country', models.CharField(default='US', help_text='2-letter country code', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether address has been validated')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('fallback_valid', 'Fallback Valid')], db_index=True, default='pending', help_text='Validation result status', max_length=20)),
                ('validation_error', models.TextField(blank=True, help_text='Validation error message if invalid', null=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text='When address was last validated', null=True)),
                ('validated_by_provider', models.CharField(blank=True, choices=[('usps', 'USPS'), ('google', 'Google Maps'), ('smarty', 'Smarty Streets'), ('lob', 'Lob')], help_text='Which API provider validated this address', max_length=20, null=True)),
                ('original_input', models.JSONField(blank=True, default=dict, help_text='Original address before validation')),
                ('normalized_address', models.JSONField(blank=True, help_text='Normalized address returned by validation API', null=True)),
                ('shipment', models.ForeignKey(help_text='Parent shipment', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shipping.shipment')),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['shipment', 'address_type'],
                'indexes': [models.Index(fields=['shipment', 'address_type'], name='addresses_shipmen_eb2188_idx'), models.Index(fields=['validation_status'], name='addresses_validat_eba815_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('shipment', 'address_type'), name='unique_address_type_per_shipment'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['upload_session', 'status'], name='shipments_upload__c8f06f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['csv_row_number'], name='shipments_csv_row_33207b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-created_at'], name='shipments_created_cb92e4_idx'),
        ),
    ]
