# Generated by Django 5.0.1 on 2026-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingserviceselection',
            name='service_tier',
            field=models.CharField(choices=[('tier_1', 'Tier 1 (0-8 oz)'), ('tier_2', 'Tier 2 (9-16 oz)'), ('tier_3', 'Tier 3 (17-32 oz)'), ('tier_4', 'Tier 4 (33+ oz)'), ('tier_5', 'Tier 5 (16+ oz)')], help_text='Service tier based on weight', max_length=10),
        ),
    ]
